"""Initial migration.

Revision ID: bb95d6a7229c
Revises: c4ed988efa0e
Create Date: 2024-03-03 12:42:01.351237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb95d6a7229c'
down_revision = 'c4ed988efa0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.String(length=200), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###
