"""empty message

Revision ID: 096076b2d2d0
Revises: cc69c71f6177
Create Date: 2024-03-19 17:29:58.508497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096076b2d2d0'
down_revision = 'cc69c71f6177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_time', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('order_time')

    # ### end Alembic commands ###
