"""empty message

Revision ID: 1d83aae541c8
Revises: cf6954a0de97
Create Date: 2024-03-18 17:25:08.567771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d83aae541c8'
down_revision = 'cf6954a0de97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('house_number', sa.String(length=100), nullable=False),
    sa.Column('entrance_number', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.Column('products_and_quantity', sa.Text(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('discount_products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount_products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('discount', sa.INTEGER(), nullable=False),
    sa.Column('discount_percentage', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('orders')
    # ### end Alembic commands ###
