"""empty message

Revision ID: 25693ca1270f
Revises: fa4c03214971
Create Date: 2024-03-28 18:54:24.577443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25693ca1270f'
down_revision = 'fa4c03214971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_orders_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_orders', type_='foreignkey')
        batch_op.drop_column('orders')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orders', sa.INTEGER(), server_default=sa.text("('')"), nullable=True))
        batch_op.create_foreign_key('fk_user_orders', 'orders', ['orders'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_orders', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
