"""empty message

Revision ID: fa4c03214971
Revises: 3e2dcf9370b1
Create Date: 2024-03-28 18:46:13.012334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa4c03214971'
down_revision = '3e2dcf9370b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orders', sa.Integer(), nullable=True, server_default=''))
        batch_op.create_foreign_key('fk_user_orders', 'orders', ['orders'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_orders', type_='foreignkey')
        batch_op.drop_column('orders')

    # ### end Alembic commands ###
